version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=8192 --max-http-header-size=80000
      - BODY_SIZE_LIMIT=100gb
      - REQUEST_TIMEOUT=3600000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Монтируем директорию для временных файлов
      - uploads:/app/uploads
      - temp:/app/temp
    restart: unless-stopped
    # Увеличиваем лимиты ресурсов для обработки больших файлов
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    # Настройки для больших файлов
    command: >
      sh -c "
        mkdir -p /app/uploads /app/temp &&
        node server.js
      "

  # Nginx для проксирования и увеличения лимитов
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/var/www/uploads:ro
    depends_on:
      - frontend
    restart: unless-stopped

volumes:
  uploads:
  temp:
